name: on_screen_keyboard
description: On screen keyboard package for flutter web
version: 0.0.4
homepage: https://github.com/digicas/flutter_minimalistic_onscreen_keyboard
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.10.6

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
